update mode added

diff --git a/p4p1-i_Instaler b/p4p1-i_Instaler
--- a/p4p1-i_Instaler
+++ b/p4p1-i_Instaler
@@ -60,6 +60,7 @@ function Debug {
 	DEGUBED=0
 	UNDEBUG=1
 	EXE_PATH=/usr/.p4p1-o/exe/
+	HOME_PATH=/usr/.p4p1-o/
 	VER=`cat /usr/.p4p1-o/cfg/ver.cfg`
 	if [[ ! -e "p4p1-o_V$VER.exe" ]]; then
 
@@ -69,7 +70,35 @@ function Debug {
 	else
 
 		mv -v p4p1-*_V$VER.exe $EXE_PATH
+		mv -v p4p1-*_V$VER $HOME_PATH
 		exit $DEGUBED
+
+	fi
+
+}
+
+function Update {
+
+	E_NOCOMP=1
+	VER=`cat /usr/.p4p1-o/cfg/ver.cfg`
+
+	make all
+	if [[ ! -e "p4p1-o_Vx.exe" && ! -e "p4p1-s_Vx" ]]; then
+
+		mv -v p4p1-o_Vx.exe p4p1-o_V$VER.exe
+		mv -v p4p1-s_Vx p4p1-s_V$VER
+
+		rm -rf /usr/.p4p1-o/exe/*
+		mv -v p4p1-o_V$VER.exe /usr/.p4p1-o/exe/
+		rm -rf /usr/.p4p1-o/p4p1-s_V$VER
+		mv -v p4p1-s_V$VER /usr/.p4p1-o/exe/
+
+		echo "[*] Done installing bye bye"
+
+	else
+
+		echo "[!] Compile error please use the -i option"
+		exit $E_NOCOMP
 
 	fi
 
@@ -130,6 +159,7 @@ if [ "$1" = "-h" ]; then
 
 		echo "[?]Usage:"
 		echo "         ./$0  ->only mode available"
+		echo "         ./$0 -u -> Update the app"
 		echo "         ./$0 mrproper -> move the exes to version."
 		echo "         p4p1-s -> command line server tool"
 
@@ -150,8 +180,14 @@ elif [ "$1" = "-e" ]; then
 elif [ "$1" = "-i" ]; then
 
 	echo "[3] Install windows compiler for linux"
-	echo "[!] This will only work for ubuntu"
+	echo "[!] This will only work for some linx distros"
 	installComp
+
+elif [ "$1" = "-u" ]; then
+
+	echo "[4] Update the app"
+	echo "[!] Do this in a different installation zip"
+	Update
 
 elif [ ! -d "$HOME_PATH" ]; then
 
@@ -315,6 +351,7 @@ elif [ ! -d "$HOME_PATH" ]; then
 else
 
 	echo "[*] Installation already done use -d to delete EVERYTHING if you want"
+	echo "[*] Or use -e To update/debug the executables with a patch"
 
 fi
 
